#creating variables for datatypes

v_str = "123"
v_int = 12
v_float = 1.2
v_complex = 1+1j
v_seq = [1,2,3,4]
v_tuple = (5,6,7,8)
v_range = range(1,2,1)
v_dict = {1:"a",2:"b" }
v_set = set([1,2,3,4])
v_frz_set = frozenset(v_set)
v_true = True
v_false = False
v_binary = bin(2)
v_bytearray = bytearray(2)
v_mv = memoryview(v_bytearray)

print ("the datatype of v_str is", type(v_str))
print ("the datatype of v_int is", type(v_int))
print ("the datatype of v_float is", type(v_float))
print ("the datatype of v_complex is", type(v_complex))
print ("the datatype of v_seq is", type(v_seq))
print ("the datatype of v_tuple is", type(v_tuple))
print ("the datatype of v_range is", type(v_range))
print ("the datatype of v_dict is", type(v_dict))
print ("the datatype of v_set is", type(v_set))
print ("the datatype of v_frz_set is", type(v_frz_set))
print ("the datatype of v_true is", type(v_true))
print ("the datatype of v_false is", type(v_false))
print ("the datatype of v_binary is", type(v_binary))
print ("the datatype of v_bytearray is", type(v_bytearray))
print ("the datatype of v_mv is", type(v_mv))

v_str1 = int(v_str) 
print (type(v_str1))
v_str2 = float(v_str)
print (type(v_str2))
v_str3 = complex(v_str)
print (type(v_str3))
v_str4 = [v_str]
print (type(v_str4))
v_str5 = (v_str)
print (type(v_str5))
#v_str6 = range(*[v_str])
v_str7 = {'data':v_str}
print (type(v_str7))
v_str8 = set(v_str)
print (type(v_str8))
v_str9 = frozenset(v_str)
print (type(v_str9))
v_str10 = bool(v_str)
print (type(v_str10))
v_str11 = bytes(v_str1)
print (type(v_str11))
v_str12 = bytearray(v_str11)
print (type(v_str12))
v_str13 = memoryview(v_str11)
print (type(v_str13))

#for v_int
v_int1 = str(v_int) 
print (type(v_int1))
v_int2 = float(v_int)
print (type(v_int2))
v_int3 = complex(v_int)
print (type(v_int3))
v_int4 = [v_int]
print (type(v_int4))
v_int5 = (v_int)
print (type(v_int5))
v_int6 = range(v_int)
print (type(v_int6))
v_int7 = {'data':v_int}
print (type(v_int7))
#v_int8 = set(v_int)
#print (type(v_int8))
#v_int9 = frozenset(v_int)
#print (type(v_int9))
v_int10 = bool(v_int)
print (type(v_int10))
v_int11 = bytes(v_int)
print (type(v_int))
v_int12 = bytearray(v_int)
print (type(v_int))
v_int13 = memoryview(v_int12)
print (type(v_int13))

#for v_float
v_float1 = str(v_float) 
print (type(v_float1))
v_float2 = int(v_float)
print (type(v_float2))
v_float3 = complex(v_float)
print (type(v_float3))
v_float4 = [v_float]
print (type(v_float4))
v_float5 = (v_float)
print (type(v_float5))
#v_float6 = range(v_float)
#print (type(v_float6))
v_float7 = {'data':v_float}
print (type(v_float7))
#v_float8 = set(v_float)
#print (type(v_float8))
#v_float9 = frozenset(v_float)
#print (type(v_float9))
v_float10 = bool(v_float)
print (type(v_float10))
#v_float11 = bytes(v_float)
#print (type(v_float))
#v_float12 = bytearray(v_float)
#print (type(v_float))
#v_float13 = memoryview(v_float12)
#print (type(v_float13))

#for v_complex
v_complex1 = str(v_complex) 
print (type(v_complex1))
#v_complex2 = float(v_complex)
#print (type(v_complex2))
v_complex3 = complex(v_complex)
print (type(v_complex3))
v_complex4 = [v_complex]
print (type(v_complex4))
v_complex5 = (v_complex)
print (type(v_complex5))
#v_complex6 = range(v_complex)
#print (type(v_complex6))
v_complex7 = {'data':v_complex}
print (type(v_complex7))
#v_complex8 = set(v_complex)
#print (type(v_complex8))
#v_complex9 = frozenset(v_complex)
#print (type(v_complex9))
v_complex10 = bool(v_complex)
print (type(v_complex10))
#v_complex11 = bytes(v_complex)
#print (type(v_complex))
#v_complex12 = bytearray(v_complex)
#print (type(v_complex))
#_complex13 = memoryview(v_complex12)
#print (type(v_complex13))

#for v_seq
v_seq1 = str(v_seq) 
print (type(v_seq1))
#v_seq2 = float(v_seq)
#print (type(v_seq2))
#v_seq3 = complex(v_seq)
#print (type(v_seq3))
v_seq4 = [v_seq]
print (type(v_seq4))
v_seq5 = (v_seq)
print (type(v_seq5))
#v_seq6 = range(v_seq)
#print (type(v_seq6))
v_seq7 = {'data':v_seq}
print (type(v_seq7))
v_seq8 = set(v_seq)
print (type(v_seq8))
v_seq9 = frozenset(v_seq)
print (type(v_seq9))
v_seq10 = bool(v_seq)
print (type(v_seq10))
v_seq11 = bytes(v_seq)
print (type(v_seq))
v_seq12 = bytearray(v_seq)
print (type(v_seq))
v_seq13 = memoryview(v_seq12)
print (type(v_seq13))

#for v_tuple
v_tuple1 = str(v_tuple) 
print (type(v_tuple1))
#v_tuple2 = float(v_tuple)
#print (type(v_tuple2))
#v_tuple3 = complex(v_tuple)
#print (type(v_tuple3))
v_tuple4 = [v_tuple]
print (type(v_tuple4))
#v_tuple5 = int(v_tuple)
#print (type(v_tuple5))
#v_tuple6 = range(v_tuple)
#print (type(v_tuple6))
v_tuple7 = {'data':v_tuple}
print (type(v_tuple7))
v_tuple8 = set(v_tuple)
print (type(v_tuple8))
v_tuple9 = frozenset(v_tuple)
print (type(v_tuple9))
v_tuple10 = bool(v_tuple)
print (type(v_tuple10))
v_tuple11 = bytes(v_tuple)
print (type(v_tuple))
v_tuple12 = bytearray(v_tuple)
print (type(v_tuple))
v_tuple13 = memoryview(v_tuple12)
print (type(v_tuple13))

#for v_range
v_range1 = str(v_range) 
print (type(v_range1))
#v_range2 = float(v_range)
#print (type(v_range2))
#v_range3 = complex(v_range)
#print (type(v_range3))
v_range4 = [v_range]
print (type(v_range4))
v_range5 = (v_range)
print (type(v_range5))
#v_range6 = int(v_range)
#print (type(v_range6))
v_range7 = {'data':v_range}
print (type(v_range7))
v_range8 = set(v_range)
print (type(v_range8))
v_range9 = frozenset(v_range)
print (type(v_range9))
v_range10 = bool(v_range)
print (type(v_range10))
v_range11 = bytes(v_range)
print (type(v_range))
v_range12 = bytearray(v_range)
print (type(v_range))
v_range13 = memoryview(v_range12)
print (type(v_range13))

#for v_dict
v_dict1 = str(v_dict) 
print (type(v_dict1))
#v_dict2 = float(v_dict)
#print (type(v_dict2))
#v_dict3 = complex(v_dict)
#print (type(v_dict3))
v_dict4 = [v_dict]
print (type(v_dict4))
v_dict5 = (v_dict)
print (type(v_dict5))
#v_dict6 = range(v_dict)
#print (type(v_dict6))
v_dict7 = {'data':v_dict}
print (type(v_dict7))
v_dict8 = set(v_dict)
print (type(v_dict8))
v_dict9 = frozenset(v_dict)
print (type(v_dict9))
v_dict10 = bool(v_dict)
print (type(v_dict10))
v_dict11 = bytes(v_dict)
print (type(v_dict))
v_dict12 = bytearray(v_dict)
print (type(v_dict))
v_dict13 = memoryview(v_dict12)
print (type(v_dict13))

#for v_set
v_set1 = str(v_set) 
print (type(v_set1))
#v_set2 = float(v_set)
#print (type(v_set2))
#v_set3 = complex(v_set)
#print (type(v_set3))
v_set4 = [v_set]
print (type(v_set4))
v_set5 = (v_set)
print (type(v_set5))
#v_set6 = range(v_set)
#print (type(v_set6))
v_set7 = {'data':v_set}
print (type(v_set7))
#v_set8 = int(v_set)
#print (type(v_set8))
v_set9 = frozenset(v_set)
print (type(v_set9))
v_set10 = bool(v_set)
print (type(v_set10))
v_set11 = bytes(v_set)
print (type(v_set))
v_set12 = bytearray(v_set)
print (type(v_set))
v_set13 = memoryview(v_set12)
print (type(v_set13))

#for v_frz_set
v_frz_set1 = str(v_frz_set) 
print (type(v_frz_set1))
#v_frz_set2 = float(v_frz_set)
#print (type(v_frz_set2))
#v_frz_set3 = complex(v_frz_set)
#print (type(v_frz_set3))
v_frz_set4 = [v_frz_set]
print (type(v_frz_set4))
v_frz_set5 = (v_frz_set)
print (type(v_frz_set5))
#v_frz_set6 = range(v_frz_set)
#print (type(v_frz_set6))
v_frz_set7 = {'data':v_frz_set}
print (type(v_frz_set7))
v_frz_set8 = set(v_frz_set)
print (type(v_frz_set8))
#v_frz_set9 = int(v_frz_set)
#print (type(v_frz_set9))
v_frz_set10 = bool(v_frz_set)
print (type(v_frz_set10))
v_frz_set11 = bytes(v_frz_set)
print (type(v_frz_set))
v_frz_set12 = bytearray(v_frz_set)
print (type(v_frz_set))
v_frz_set13 = memoryview(v_frz_set12)
print (type(v_frz_set13))

#for v_boolean
v_true1 = str(v_true) 
print (type(v_true1))
v_true2 = float(v_true)
print (type(v_true2))
v_true3 = complex(v_true)
print (type(v_true3))
v_true4 = [v_true]
print (type(v_true4))
v_true5 = (v_true)
print (type(v_true5))
v_true6 = range(v_true)
print (type(v_true6))
v_true7 = {'data':v_true}
print (type(v_true7))
v_true8 = int(v_true)
print (type(v_true8))
#v_true9 = frozenset(v_true)
#print (type(v_true9))
v_true10 = int(v_true)
print (type(v_true10))
v_true11 = bytes(v_true)
print (type(v_true))
v_true12 = bytearray(v_true)
print (type(v_true))
v_true13 = memoryview(v_true12)
print (type(v_true13))

#for v_binary
v_binary1 = str(v_binary) 
print (type(v_binary1))
#v_binary2 = float(v_binary)
#print (type(v_binary2))
#v_binary3 = complex(v_binary)
#print (type(v_binary3))
v_binary4 = [v_binary]
print (type(v_binary4))
v_binary5 = (v_binary)
print (type(v_binary5))
#v_binary6 = range(v_binary)
#print (type(v_binary6))
v_binary7 = {'data':v_binary}
print (type(v_binary7))
v_binary8 = set(v_binary)
print (type(v_binary8))
v_binary9 = frozenset(v_binary)
print (type(v_binary9))
v_binary10 = bool(v_binary)
print (type(v_binary10))
#v_binary11 = int(v_binary)
#print (type(v_binary))
#v_binary12 = bytearray(v_binary)
#print (type(v_binary))
#v_binary13 = memoryview(v_binary)
#print (type(v_binary13))

#for v_bytearray
v_bytearray1 = str(v_bytearray) 
print (type(v_bytearray1))
#v_bytearray2 = float(v_bytearray)
#print (type(v_bytearray2))
#v_bytearray3 = complex(v_bytearray)
#print (type(v_bytearray3))
v_bytearray4 = [v_bytearray]
print (type(v_bytearray4))
v_bytearray5 = (v_bytearray)
print (type(v_bytearray5))
#v_bytearray6 = range(v_bytearray)
#print (type(v_bytearray6))
v_bytearray7 = {'data':v_bytearray}
print (type(v_bytearray7))
#v_bytearray8 = int(v_bytearray)
#print (type(v_bytearray8))
v_bytearray9 = frozenset(v_bytearray)
print (type(v_bytearray9))
v_bytearray10 = bool(v_bytearray)
print (type(v_bytearray10))
v_bytearray11 = bytes(v_bytearray)
print (type(v_bytearray))
v_bytearray12 = set(v_bytearray)
print (type(v_bytearray))
v_bytearray13 = memoryview(v_bytearray)
print (type(v_bytearray13))

#for v_mv
v_mv1 = str(v_mv) 
print (type(v_mv1))
#v_mv2 = float(v_mv)
#print (type(v_mv2))
#v_mv3 = complex(v_mv)
#print (type(v_mv3))
v_mv4 = [v_mv]
print (type(v_mv4))
v_mv5 = (v_mv)
print (type(v_mv5))
#v_mv6 = range(v_mv)
#print (type(v_mv6))
v_mv7 = {'data':v_mv}
print (type(v_mv7))
#v_mv8 = int(v_mv)
#print (type(v_mv8))
v_mv9 = frozenset(v_mv)
print (type(v_mv9))
v_mv10 = bool(v_mv)
print (type(v_mv10))
v_mv11 = bytes(v_mv)
print (type(v_mv11))
v_mv12 = bytearray(v_mv)
print (type(v_mv12))
v_mv13 = set(v_set12)
print (type(v_set13))


