import datetime
dob = datetime.date(1996,5,23)
print(dob.strftime("%B %drd %Y"))
print(dob.strftime("%drd %B %Y"))
print(dob.strftime("%B %d,%Y"))
print(dob.strftime("%b-%d-%Y"))
print(dob.strftime("%m-%d-%y"))
print(dob.strftime("%m-%d-%Y"))
print(dob.strftime("%d/%m/%Y"))
print(dob.strftime("%B the %drd, the year %Y"))